services:
  - type: web
    name: rfb-v2-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: rfb-v2-db
          property: connectionString
      - key: MAIL_TO
        value: admin@rutherglenfb.com.au
      - key: CORS_ORIGINS
        value: "*"
      - key: TOTP_ISSUER
        value: Rutherglen Fire Brigade

databases:
  - name: rfb-v2-db
    plan: free
